### ISSUE TITLE
Suggestion: Add configuration for features

### ISSUE THREAD

**Issue by TwentySeventhLetter** [Happy1speed/glidelytra#1]
Hi! I really like the concept behind this mod, and the boost rings are really satisfying to use, but I have some other mods on that tweak the way Elytra work, and the design of each mod sort of conflicts. I think it would be good if a few of the features in your mod were configurable so they could be disabled or adjusted. The key mechanics I have in mind are the gradual durability regeneration of Elytra when not flying, the cooldown on rockets, and the disabling of elytra on taking damage. I'm currently using the Aileron mod for example and it already completely disables boosting with rockets in favor of a cosmetic particle trail, so the cooldown effect is at odds with the altered design.

Another smaller note is that I felt the construction for the multiblock structure was slightly unintuitive, though I realize that can be configured with datapacks. I think the custom blocks the mod adds feel a little redundant considering they don't serve any other purpose, so I'm not sure if more is planned for them, but again it's not nearly as big of a deal. Thanks for making this cool mod, I'm always looking for creative takes on nerfing elytra in a way that lets them still be fun!

**Comment by Happy1speed** [comment]
As soon as I figure out how to make configs that sync with the server, ill add some configuration!

The Multiblock isn't final and maybe too expensive to build right now. 

As for the Phantom membrane gel blocks, they do have a purpose. 
They have no collision, allowing the building of vertical boost rings.
Since you get boosted in the direction you're facing, you can just go up or down through the base structure. 
Just make sure you have a phantom membrane gel block under the Aerial Accelerator so that it disables its collision.

**Comment by TwentySeventhLetter** [comment]
I see, good to hear about the configs! I think the main issue with the phantom blocks is it's difficult to tell the different phantom blocks apart from one another, and I didn't realize you could build the rings vertically (which is super cool). Even in that case though, you phase through all 3 of them, and I didn't even know the center block would become intangible under the right conditions.

I think the booster rings are very strong so I wouldn't necessarily take issue with the cost _that_ much; I think 4 resource blocks per functional ring is pretty good considering the cost of beacons. That said though, the phantom block that serves the same purpose costing 4 gold blocks might be a bit gratuitous. I think in general, each of the three should have some meaningful identity that makes them distinct from each other to aid players in deciphering which goes where and why.

It seems like the design you have currently is that there's sort of a "mundane" block serving as the literal ring on the outside, then a chiseled or fancy variant, and then the resource-cost giving it some kind of power source. To me, the weak link here is the role of the chiseled variant, as in vanilla, the multiblock structures we have to draw inspiration from both have a central function block (the beacon or conduit), and their constituent structures, which seem to serve the purpose of either the relatively mundane like the conduit's prismarine variants, or the resource-cost for the beacon's pyramid.

I think it may be best to simplify the design and remove the "chiseled" group and either absorb its block list into the "mundane", or cut the mundane group and necessitate the fancier blocks (if you want the rings to feel a little more special/selective). If there are other design goals you have in mind that aren't apparent, feel free to share here, but that's just my two cents. Once again, really cool mod (and I love the sound effect for hitting the rings, very satisfying).

**Comment by TwentySeventhLetter** [comment]
Haha I just looked at the recipe again, I didn't realize it was 4 gold blocks for 4 pure membrane, I think the recipe is completely fine then

**Comment by Happy1speed** [comment]
Maybe I will just simplify the design like you said and absorb the chiseled blocks into the mundane block group.

Also, I worded the "vertical boost rings" part wrongly, I meant to say that with the phantom membrane gel blocks as the base, it can work vertically since you can just fly through the base at that point.

**Comment by Happy1speed** [comment]
Also I think im just going to do a simple config for now. I think its going to be too much of a hassle to get an advanced config library working. The config options don't really need to be synced with the server.
